site_name: Chatbot API Documentation
site_url: https://berangeregallais.github.io/chatbot-docs
nav:
  - Home: index.md
  - Quickstart: quickstart.md
  - API Endpoints:
      - Send a message: api/chat_send.md
      - History: api/chat_history.md
      - Analytics: api/chat_analytics.md
  - Authentication: auth.md
  - Error Handling: errors.md
  - Webhooks: webhooks.md
  - Code examples: examples.md
  - Use cases: usecases.md
  - Rate Limits & Best Practices: rate_limits.md
  - Monitoring & Analytics: monitoring.md
  - Playground: playground.md
  - 📘 Project Info:
      - About This Documentation: about.md
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
